//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Alarm_Clock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarm_log
    {
        public int indexID { get; set; }
        public string alarmID { get; set; }
        public string yellowStatus { get; set; }
        public string redStatus { get; set; }
        public string alarmUsed { get; set; }
        public Nullable<System.DateTime> logTime { get; set; }
    }
}
