//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Alarm_Clock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string username { get; set; }
        public string userPassword { get; set; }
        public Nullable<System.DateTime> redAlarmDateTime { get; set; }
        public Nullable<System.DateTime> yellowAlarmDateTime { get; set; }
        public Nullable<int> redAlarmCount { get; set; }
        public Nullable<int> yellowAlarmCount { get; set; }
        public Nullable<bool> isAsleep { get; set; }
    }
}
