//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Alarm_Clock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_list
    {
        public string userID { get; set; }
        public string sleepStatus { get; set; }
        public string sleepCritical { get; set; }
        public Nullable<System.TimeSpan> wakeTime { get; set; }
        public string password { get; set; }
    }
}
